server.port: 8080
spring:
  cloud:
    function:
    #   definition: toUpperCase;data;consume
      definition: consume
    stream:
      default-binder: kafka
      kafka.binder.brokers: kafka-kafka-brokers.kafka:9092
      bindings:
        consume-in-0:
          destination: new-topic
        
# spring:
#   cloud:
#     stream:
#       defaultBinder: kafka
#       bindings:
#         input:
#           destination: new-topic
#           consumer:
#             maxAttempts: 3
#             backOffInitialInterval: 500
#             backOffMaxInterval: 1000
#             backOffMultiplier: 2.0
  
#       kafka:
#         bindings:
#           input:
#             consumer:
#               enableDlq: true
#         binder.brokers: kafka-kafka-brokers.kafka:9092



# spring.cloud.stream:
#   defaultBinder: kafka
#   default.contentType: application/json
#   bindings.input:
#     destination: new-topic

# spring.cloud.stream.bindings.input.consumer:
#   maxAttempts: 3
#   backOffInitialInterval: 500
#   backOffMaxInterval: 1000
#   backOffMultiplier: 2.0

# spring.cloud.stream.kafka.bindings.input.consumer:
#   enableDlq: true

# spring.cloud.stream.kafka.binder:
#   brokers: kafka-kafka-brokers.kafka
#   defaultBrokerPort: 9092

# logging:
#   level:
#     root: INFO